export const PlaceholderVisual = () => {
  return (
    <svg
      width="64"
      height="83"
      viewBox="0 0 64 83"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
    >
      <g opacity="0.5" filter="url(#filter0_d_2612_7)">
        <rect x="8" y="3" width="48" height="52" rx="2" fill="#FAFBFF" />
        <rect
          x="8.125"
          y="3.125"
          width="47.75"
          height="51.75"
          rx="1.875"
          stroke="#DCDDEA"
          strokeWidth="0.25"
        />
      </g>
      <g filter="url(#filter1_d_2612_7)">
        <rect x="2" y="7" width="60" height="75" rx="2" fill="#FAFBFF" />
        <rect
          x="2.125"
          y="7.125"
          width="59.75"
          height="74.75"
          rx="1.875"
          stroke="#DCDDEA"
          strokeWidth="0.25"
        />
      </g>
      <rect
        x="13"
        y="13"
        width="6"
        height="2"
        rx="1"
        fill="#63677D"
        fillOpacity="0.4"
      />
      <rect
        x="20"
        y="13"
        width="14"
        height="2"
        rx="1"
        fill="#63677D"
        fillOpacity="0.4"
      />
      <rect
        x="5"
        y="19"
        width="54"
        height="15"
        rx="2"
        fill="#63677D"
        fillOpacity="0.1"
      />
      <rect
        x="5"
        y="42"
        width="54"
        height="6"
        rx="2"
        fill="#63677D"
        fillOpacity="0.1"
      />
      <rect
        x="5"
        y="50"
        width="54"
        height="6"
        rx="2"
        fill="#63677D"
        fillOpacity="0.1"
      />
      <rect
        x="5"
        y="58"
        width="54"
        height="6"
        rx="2"
        fill="#63677D"
        fillOpacity="0.1"
      />
      <rect
        x="5"
        y="72"
        width="26"
        height="6"
        rx="2"
        fill="#63677D"
        fillOpacity="0.1"
      />
      <rect
        x="33"
        y="72"
        width="26"
        height="6"
        rx="2"
        fill="#63677D"
        fillOpacity="0.1"
      />
      <rect
        x="5"
        y="11"
        width="6"
        height="6"
        rx="3"
        fill="#63677D"
        fillOpacity="0.2"
      />
      <rect
        x="5"
        y="38"
        width="7"
        height="2"
        rx="1"
        fill="#63677D"
        fillOpacity="0.4"
      />
      <rect
        x="5"
        y="68"
        width="7"
        height="2"
        rx="1"
        fill="#63677D"
        fillOpacity="0.4"
      />
      <defs>
        <filter
          id="filter0_d_2612_7"
          x="6"
          y="0"
          width="52"
          height="56"
          filterUnits="userSpaceOnUse"
          colorInterpolationFilters="sRGB"
        >
          <feFlood floodOpacity="0" result="BackgroundImageFix" />
          <feColorMatrix
            in="SourceAlpha"
            type="matrix"
            values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0"
            result="hardAlpha"
          />
          <feOffset dy="-1" />
          <feGaussianBlur stdDeviation="1" />
          <feComposite in2="hardAlpha" operator="out" />
          <feColorMatrix
            type="matrix"
            values="0 0 0 0 0.803922 0 0 0 0 0.811765 0 0 0 0 0.847059 0 0 0 0.2 0"
          />
          <feBlend
            mode="normal"
            in2="BackgroundImageFix"
            result="effect1_dropShadow_2612_7"
          />
          <feBlend
            mode="normal"
            in="SourceGraphic"
            in2="effect1_dropShadow_2612_7"
            result="shape"
          />
        </filter>
        <filter
          id="filter1_d_2612_7"
          x="0"
          y="4"
          width="64"
          height="79"
          filterUnits="userSpaceOnUse"
          colorInterpolationFilters="sRGB"
        >
          <feFlood floodOpacity="0" result="BackgroundImageFix" />
          <feColorMatrix
            in="SourceAlpha"
            type="matrix"
            values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0"
            result="hardAlpha"
          />
          <feOffset dy="-1" />
          <feGaussianBlur stdDeviation="1" />
          <feComposite in2="hardAlpha" operator="out" />
          <feColorMatrix
            type="matrix"
            values="0 0 0 0 0.803922 0 0 0 0 0.811765 0 0 0 0 0.847059 0 0 0 0.2 0"
          />
          <feBlend
            mode="normal"
            in2="BackgroundImageFix"
            result="effect1_dropShadow_2612_7"
          />
          <feBlend
            mode="normal"
            in="SourceGraphic"
            in2="effect1_dropShadow_2612_7"
            result="shape"
          />
        </filter>
      </defs>
    </svg>
  );
};
